version: "3.3"

services:
  postgresdb:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=${DOCKER_DATABASE_PASSWORD}
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "5433" # Publishes 5433 to other containers but NOT to host machine
    command: -p 5433

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgresdb
