version: "3.3"

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - 1300:80
    volumes:
      - static_volume:/nginx/static
    depends_on:
      - web
    restart: "on-failure"

  postgresdb:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=${DOCKER_DATABASE_PASSWORD}
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "5434" # Publishes specific port to other containers but NOT to host machine
    command: -p 5434
    restart: "on-failure"

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgresdb
    restart: "on-failure"

volumes:
  static_volume: