# Generated by Django 2.2 on 2020-11-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_auto_20201110_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(default=False, max_length=150),
        ),
    ]
