# Generated by Django 2.2 on 2020-11-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_auto_20201110_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default=False, max_length=100, unique=True),
        ),
    ]
