# Generated by Django 2.2 on 2020-11-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0013_auto_20201110_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
