# Generated by Django 2.2 on 2020-11-10 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0019_auto_20201110_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
