# Generated by Django 2.2 on 2020-11-10 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0020_remove_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
