# Generated by Django 2.2 on 2020-11-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0023_auto_20201110_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='Some location', max_length=150),
        ),
    ]
