# Generated by Django 2.2 on 2020-11-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0025_auto_20201111_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='some_new_field1',
            field=models.CharField(default='Some value', max_length=50),
        ),
    ]
