# Generated by Django 2.2 on 2020-11-11 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0026_customuser_some_new_field1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='some_new_field1',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
