# Generated by Django 2.2 on 2020-11-11 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('blog_app', '0007_auto_20201111_2103'),
        ('user_app', '0027_auto_20201111_2046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
