# Generated by Django 2.2 on 2020-11-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='some_new_field',
            field=models.TextField(default=''),
        ),
    ]
