# Generated by Django 2.2 on 2020-11-11 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_post_some_new_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='some_new_field',
        ),
    ]
