# Generated by Django 2.2 on 2020-11-11 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_remove_post_some_new_field'),
    ]

    operations = [
    ]
