# Generated by Django 2.2 on 2020-11-11 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_auto_20201111_2047'),
    ]

    operations = [
    ]
