# Generated by Django 2.2 on 2020-11-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_auto_20201111_2111'),
        ('blog_app', '0002_auto_20201111_1329'),
    ]

    operations = [
    ]
