# Generated by Django 2.2 on 2020-11-18 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_auto_20201118_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
