# Generated by Django 2.2 on 2020-12-11 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0015_post_total_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='total_views',
        ),
    ]
