# Generated by Django 2.2 on 2020-12-15 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0018_auto_20201215_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportpost',
            name='reports',
            field=models.ManyToManyField(blank=True, related_name='post_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
