# Generated by Django 2.2 on 2020-12-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0020_auto_20201215_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpost',
            name='total_reports',
            field=models.IntegerField(default=0),
        ),
    ]
