# Generated by Django 3.1.4 on 2021-01-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0022_auto_20210112_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tagline',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
