# Generated by Django 3.1.4 on 2021-01-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0023_auto_20210115_1415'),
    ]

    operations = [

    ]
